### PR TITLE
Add unit tests for Feedback service

### PR DESCRIPTION
**Pull request by lukasotocerny**
Blocked: Waiting for a class implemeting FeedbackDAO interface

### CODE REVIEW

**Review by bbaayezi — COMMENTED** [review]
So far so good, but I think most of these test cases are designed by "how the system should work". I think we could add more tests cases that meant to "break the system".
I'm not sure about it though, since the feedback service impl gets it input via feedback controller, if we covers more test cases in feedback controller it should be fine. Whatdo you think?

**Comment by lukasotocerny** [comment]
What do you mean by test cases that break the system? Yes, these test cases are there to make sure that no one breaks our requriements in the future.

**Comment by bbaayezi** [comment]
> What do you mean by test cases that break the system? Yes, these test cases are there to make sure that no one breaks our requriements in the future.

for example, we could think of more cases when the system could go wrong, and write the test cases to ensure that we did the proper error handling.
But current test cases are fine, we could merge them first and add any further test cases in the future.

**Comment by lukasotocerny** [comment]
Ok, will merge for now

**Pull request merged**
